fluent
hamy11/fluent-api pull request #1
Opened 2017-11-20 23:56 UTC by hamy11

2017-11-20 23:57 UTC, hamy11 commented
@Qoter

2017-11-23 06:52 UTC, qoter requested changes

2017-11-23 06:52 UTC, qoter commented on ObjectPrinting/PrintingConfig.cs
> +            if (!excludedTypes.Contains(typeof(TPropType)))
Можно не проверять

2017-11-23 06:52 UTC, qoter commented on ObjectPrinting/PrintingConfig.cs
> +            if (!excludedProperties.Contains(propInfo))
Тоже можно не проверять

2017-11-23 06:52 UTC, qoter commented on ObjectPrinting/PrintingConfig.cs
>              return sb.ToString();
```
Person
	Id = Guid

	Name =                   AL

Person
	Id = Guid

	Name = Alex
	Height = 10,7
	Age = 19

Person
	Id = Guid

	Name = Alex
	Height = 10,7
```
На тесте Demo остаются пустые строки

2017-11-23 06:52 UTC, qoter commented on ObjectPrinting/Tests/ObjectPrinterAcceptanceTests.cs
> +        public void ObjectPrinter_ShouldExcludeTypes_WhenExcludingDouble()
Не пиши ObjectPrinter_Should каждый раз, лучше вынеси в название класса. А то когда начинаешь писать ObjectPrinter.For в IntelliSense куча тестов перед нужным вариантом, приходится до конца писать))

2017-11-23 19:39 UTC, hamy11 commented
@Qoter

2017-11-26 18:29 UTC, qoter approved these changes
Принято

2017-11-29 14:19 UTC, merged